### ISSUE TITLE
Opening files in `terminal`

### ISSUE THREAD

**Issue by C-STYR** [C-STYR/GitHubTrainer#27]
Please do the following: 

1. Add a markdown file with content that explains how to open a file **_within_** the terminal. 
2. Add a markdown file with content that explains how to open a file to VS Code with a terminal command.  Hint: the command is `code .` but you'll have to figure out how configure it.

**Comment by a-hend** [comment]
Ahhhhh, yeah.  I found this online in some older website posts, but I couldn't find shell commands to configure `code` when I searched for it in vs code so I thought maybe it was outdated...I'll go dig it up again and figure it out.

**Comment by a-hend** [comment]
I'm not sure I understand number one above.  I thought I completed it, then realized that I used the `code` command, so I must have completed number two instead.

<img width="517" alt="Screen Shot 2022-10-08 at 9 20 42 AM" src="https://user-images.githubusercontent.com/113646550/194719793-c683f785-175e-4b90-b656-d83f97ca1d45.png">

**Comment by C-STYR** [comment]
Yep, you completed number 2, although you added that file to an already existing PR rather than a new PR.  (In general, each issue should have its own PR). For number 1, `terminal` has a built in text editor, and you can use it by typing a command followed by the filename.  That's all the hint I'll give you.

**Comment by a-hend** [comment]
Ok, as to the PR.  I couldn't create a new branch because the folders that I had created that I wanted to put the file in weren't merged to origin yet, so when I did create a new branch at first, the `textfiles/` folder disappeared.  So I tried using the branch that I had created for the original issue, #22, and they popped back up and I was able to create the new file in `textfiles/subfile/`.  Would you recommend that I do something different in the future?
